# Generated by Django 3.1.7 on 2021-03-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genderChoice',
            field=models.CharField(choices=[('T', 'Trance'), ('M', 'Man'), ('W', 'Woman')], default='T', max_length=1),
        ),
    ]
