# Generated by Django 3.1.7 on 2021-03-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_genderchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='choice',
            field=models.BooleanField(default=False, verbose_name='Просто галочка :3'),
        ),
    ]
